// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: api/v1/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerActionRequest_Action int32

const (
	PlayerActionRequest_UP   PlayerActionRequest_Action = 0
	PlayerActionRequest_DOWN PlayerActionRequest_Action = 1
	PlayerActionRequest_NONE PlayerActionRequest_Action = 2
)

// Enum value maps for PlayerActionRequest_Action.
var (
	PlayerActionRequest_Action_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "NONE",
	}
	PlayerActionRequest_Action_value = map[string]int32{
		"UP":   0,
		"DOWN": 1,
		"NONE": 2,
	}
)

func (x PlayerActionRequest_Action) Enum() *PlayerActionRequest_Action {
	p := new(PlayerActionRequest_Action)
	*p = x
	return p
}

func (x PlayerActionRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerActionRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_game_proto_enumTypes[0].Descriptor()
}

func (PlayerActionRequest_Action) Type() protoreflect.EnumType {
	return &file_api_v1_game_proto_enumTypes[0]
}

func (x PlayerActionRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerActionRequest_Action.Descriptor instead.
func (PlayerActionRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{7, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StartPVEGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPVEGameRequest) Reset() {
	*x = StartPVEGameRequest{}
	mi := &file_api_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPVEGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPVEGameRequest) ProtoMessage() {}

func (x *StartPVEGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPVEGameRequest.ProtoReflect.Descriptor instead.
func (*StartPVEGameRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *StartPVEGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StartPVPGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPVPGameRequest) Reset() {
	*x = StartPVPGameRequest{}
	mi := &file_api_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPVPGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPVPGameRequest) ProtoMessage() {}

func (x *StartPVPGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPVPGameRequest.ProtoReflect.Descriptor instead.
func (*StartPVPGameRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *StartPVPGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BallX         int32                  `protobuf:"varint,1,opt,name=ball_x,json=ballX,proto3" json:"ball_x,omitempty"`
	BallY         int32                  `protobuf:"varint,2,opt,name=ball_y,json=ballY,proto3" json:"ball_y,omitempty"`
	PlayerScore   int32                  `protobuf:"varint,3,opt,name=player_score,json=playerScore,proto3" json:"player_score,omitempty"`
	AiScore       int32                  `protobuf:"varint,4,opt,name=ai_score,json=aiScore,proto3" json:"ai_score,omitempty"`
	PaddleY       int32                  `protobuf:"varint,5,opt,name=paddle_y,json=paddleY,proto3" json:"paddle_y,omitempty"`
	AiPaddleY     int32                  `protobuf:"varint,6,opt,name=ai_paddle_y,json=aiPaddleY,proto3" json:"ai_paddle_y,omitempty"`
	GameId        string                 `protobuf:"bytes,7,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_api_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameState) GetBallX() int32 {
	if x != nil {
		return x.BallX
	}
	return 0
}

func (x *GameState) GetBallY() int32 {
	if x != nil {
		return x.BallY
	}
	return 0
}

func (x *GameState) GetPlayerScore() int32 {
	if x != nil {
		return x.PlayerScore
	}
	return 0
}

func (x *GameState) GetAiScore() int32 {
	if x != nil {
		return x.AiScore
	}
	return 0
}

func (x *GameState) GetPaddleY() int32 {
	if x != nil {
		return x.PaddleY
	}
	return 0
}

func (x *GameState) GetAiPaddleY() int32 {
	if x != nil {
		return x.AiPaddleY
	}
	return 0
}

func (x *GameState) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type PlayerActionRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	GameId        string                     `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Action        PlayerActionRequest_Action `protobuf:"varint,2,opt,name=action,proto3,enum=pingpong.v1.PlayerActionRequest_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionRequest) Reset() {
	*x = PlayerActionRequest{}
	mi := &file_api_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionRequest) ProtoMessage() {}

func (x *PlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionRequest.ProtoReflect.Descriptor instead.
func (*PlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerActionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerActionRequest) GetAction() PlayerActionRequest_Action {
	if x != nil {
		return x.Action
	}
	return PlayerActionRequest_UP
}

type PlayerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionResponse) Reset() {
	*x = PlayerActionResponse{}
	mi := &file_api_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionResponse) ProtoMessage() {}

func (x *PlayerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionResponse.ProtoReflect.Descriptor instead.
func (*PlayerActionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_v1_game_proto protoreflect.FileDescriptor

const file_api_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/game.proto\x12\vpingpong.v1\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\".\n" +
	"\x13StartPVEGameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x13StartPVPGameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xcb\x01\n" +
	"\tGameState\x12\x15\n" +
	"\x06ball_x\x18\x01 \x01(\x05R\x05ballX\x12\x15\n" +
	"\x06ball_y\x18\x02 \x01(\x05R\x05ballY\x12!\n" +
	"\fplayer_score\x18\x03 \x01(\x05R\vplayerScore\x12\x19\n" +
	"\bai_score\x18\x04 \x01(\x05R\aaiScore\x12\x19\n" +
	"\bpaddle_y\x18\x05 \x01(\x05R\apaddleY\x12\x1e\n" +
	"\vai_paddle_y\x18\x06 \x01(\x05R\taiPaddleY\x12\x17\n" +
	"\agame_id\x18\a \x01(\tR\x06gameId\"\x95\x01\n" +
	"\x13PlayerActionRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12?\n" +
	"\x06action\x18\x02 \x01(\x0e2'.pingpong.v1.PlayerActionRequest.ActionR\x06action\"$\n" +
	"\x06Action\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\b\n" +
	"\x04NONE\x10\x02\"0\n" +
	"\x14PlayerActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8d\x03\n" +
	"\vGameService\x12I\n" +
	"\bRegister\x12\x1c.pingpong.v1.RegisterRequest\x1a\x1d.pingpong.v1.RegisterResponse\"\x00\x12@\n" +
	"\x05Login\x12\x19.pingpong.v1.LoginRequest\x1a\x1a.pingpong.v1.LoginResponse\"\x00\x12L\n" +
	"\fStartPVEGame\x12 .pingpong.v1.StartPVEGameRequest\x1a\x16.pingpong.v1.GameState\"\x000\x01\x12L\n" +
	"\fStartPVPGame\x12 .pingpong.v1.StartPVPGameRequest\x1a\x16.pingpong.v1.GameState\"\x000\x01\x12U\n" +
	"\fPlayerAction\x12 .pingpong.v1.PlayerActionRequest\x1a!.pingpong.v1.PlayerActionResponse\"\x00B\x0fZ\rapi/v1;gamev1b\x06proto3"

var (
	file_api_v1_game_proto_rawDescOnce sync.Once
	file_api_v1_game_proto_rawDescData []byte
)

func file_api_v1_game_proto_rawDescGZIP() []byte {
	file_api_v1_game_proto_rawDescOnce.Do(func() {
		file_api_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_game_proto_rawDesc), len(file_api_v1_game_proto_rawDesc)))
	})
	return file_api_v1_game_proto_rawDescData
}

var file_api_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_game_proto_goTypes = []any{
	(PlayerActionRequest_Action)(0), // 0: pingpong.v1.PlayerActionRequest.Action
	(*RegisterRequest)(nil),         // 1: pingpong.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 2: pingpong.v1.RegisterResponse
	(*LoginRequest)(nil),            // 3: pingpong.v1.LoginRequest
	(*LoginResponse)(nil),           // 4: pingpong.v1.LoginResponse
	(*StartPVEGameRequest)(nil),     // 5: pingpong.v1.StartPVEGameRequest
	(*StartPVPGameRequest)(nil),     // 6: pingpong.v1.StartPVPGameRequest
	(*GameState)(nil),               // 7: pingpong.v1.GameState
	(*PlayerActionRequest)(nil),     // 8: pingpong.v1.PlayerActionRequest
	(*PlayerActionResponse)(nil),    // 9: pingpong.v1.PlayerActionResponse
}
var file_api_v1_game_proto_depIdxs = []int32{
	0, // 0: pingpong.v1.PlayerActionRequest.action:type_name -> pingpong.v1.PlayerActionRequest.Action
	1, // 1: pingpong.v1.GameService.Register:input_type -> pingpong.v1.RegisterRequest
	3, // 2: pingpong.v1.GameService.Login:input_type -> pingpong.v1.LoginRequest
	5, // 3: pingpong.v1.GameService.StartPVEGame:input_type -> pingpong.v1.StartPVEGameRequest
	6, // 4: pingpong.v1.GameService.StartPVPGame:input_type -> pingpong.v1.StartPVPGameRequest
	8, // 5: pingpong.v1.GameService.PlayerAction:input_type -> pingpong.v1.PlayerActionRequest
	2, // 6: pingpong.v1.GameService.Register:output_type -> pingpong.v1.RegisterResponse
	4, // 7: pingpong.v1.GameService.Login:output_type -> pingpong.v1.LoginResponse
	7, // 8: pingpong.v1.GameService.StartPVEGame:output_type -> pingpong.v1.GameState
	7, // 9: pingpong.v1.GameService.StartPVPGame:output_type -> pingpong.v1.GameState
	9, // 10: pingpong.v1.GameService.PlayerAction:output_type -> pingpong.v1.PlayerActionResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_game_proto_init() }
func file_api_v1_game_proto_init() {
	if File_api_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_game_proto_rawDesc), len(file_api_v1_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_game_proto_goTypes,
		DependencyIndexes: file_api_v1_game_proto_depIdxs,
		EnumInfos:         file_api_v1_game_proto_enumTypes,
		MessageInfos:      file_api_v1_game_proto_msgTypes,
	}.Build()
	File_api_v1_game_proto = out.File
	file_api_v1_game_proto_goTypes = nil
	file_api_v1_game_proto_depIdxs = nil
}
